#!/bin/bash
clear
#----------- BANNER-------------------

echo "

 _  _    __    __   
( )/ )  /__\  (  )  
 )  (  /(__)\  )(__ 
(_)\_)(__)(__)(____)


"
cd /tmp/

#------------------source list--------------

echo "
deb http://deb.debian.org/debian buster main
deb-src http://deb.debian.org/debian buster main

deb http://deb.debian.org/debian-security/ buster/updates main
deb-src http://deb.debian.org/debian-security/ buster/updates main

deb http://deb.debian.org/debian buster-updates main
deb-src http://deb.debian.org/debian buster-updates main
" > /etc/apt/sources.list

#-----------------vbox ----------------------

apt update && apt install build-essential module-assistant dkms -y
m-a prepare
FILE=/media/cdrom0/VBoxLinuxAdditions.run
if [ ! -f "$FILE" ]; then
	while true; do
    	read -p "Insert Guest additions from 'Devices > Insert Guest addtions CD Image'. Once done press "Y" to continue: " yn
    	case $yn in
       	 [Yy]* ) break;;
       	 [Nn]* ) exit;;
       	 * ) echo "Please Insert Guest additions.";;
   	 esac
	done
fi
cp /media/cdrom0/VBoxLinuxAdditions.run ./
chmod 777 VBoxLinuxAdditions.run
./VBoxLinuxAdditions.run
rm VBo*

#------------------Display--------------------

apt install plank materia-gtk-theme fonts-roboto -y
nohup plank &
wget https://github.com/3kara/3kara-OS/raw/master/Flat-Remix-Blue-Dark.tar.xz -P /tmp/
tar xvf /tmp/Flat-Remix-Blue-Dark.tar.xz -C /usr/share/icons/
rm Flat-Remix-Blue-Dark.tar.xz
xfconf-query -c xsettings -p /Net/ThemeName -s "Materia-Dark"
xfconf-query -c xfwm4 -p /general/theme -s "Materia-dark"
xfconf-query -c xsettings -p /Net/IconThemeName -s "Flat-Remix-Blue-Dark"
xfconf-query -c xfwm4 -p /general/show_dock_shadow -s false
cp /usr/share/applications/plank.desktop /etc/xdg/autostart/plank.desktop
rm ~/.config/plank/dock1/launchers/firefox-esr-1.dockitem ~/.config/plank/dock1/launchers/org.xfce.Parole.dockitem ~/.config/plank/dock1/launchers/io.github.quodlibet.QuodLibet.dockitem
(
echo [PlankDockItemPreferences]
echo Launcher=file:///usr/share/applications/xfce4-terminal.desktop
)>"~/.config/plank/dock1/launchers/xfce4-terminal.dockitem"
(
echo [PlankDockItemPreferences]
echo Launcher=file:///usr/share/applications/Thunar.desktop
)>"~/.config/plank/dock1/launchers/Thunar.dockitem"
echo "GRUB_BACKGROUND="/root/Downloads/kal_grub_bg.png"" >> /etc/default/grub
update-grub

#-----------------   ---------------------------


